config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    mount Cms9::Engine => '/cms9' # or DEF_ROUTE where your Cms9 route is mounted
  end

  root 'posts#index'

  resources :posts, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def cms9_admin?
    return true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
  	if params[:name].blank?
  		@posts = Cms9::Post.all.limit(20).order('created_at desc')
  	else
  		post_definition = Cms9::PostDefinition.where(name: params[:name]).first
  		@posts = post_definition.posts
  	end
  end

  def show
    @post = Cms9::Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer style="position: fixed; width: 100%; bottom: 0;">
  <div class="footer-holder">
      <div class="container">
        <div class="row">
        	<p>Copyright 2016. Klika d.o.o. Sarajevo. All Rights Reserved.</p>
        </div>
      </div>
   </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-info">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-material-light-blue-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("cms9/favicon-32.png"), root_path, class: 'logo' %>
    </div>
    <div class="navbar-collapse collapse navbar-material-light-blue-collapse">
      <ul class="nav navbar-nav">
        <% Cms9::PostDefinition.all.each do |post_def| %>
          <% if post_def.posts.any? %>
            <li><%= link_to post_def.name , posts_path({name: post_def.name}) %></li>
          <% end %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" data-target="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
              <b class="caret"></b>
              <div class="ripple-container"></div>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to cms9_path do %>
                  Cms9 Administration
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  Logout
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cms9Demo</title>
    <%= csrf_meta_tags %>
      <%= favicon_link_tag 'images/cms9/favicon-16.png', type: 'image/png' %>
      <%= favicon_link_tag 'cms9/favicon-32.png', type: 'image/png' %>
      <%= favicon_link_tag 'cms9/favicon-64.png', type: 'image/png' %>
      <%= favicon_link_tag 'cms9/favicon-64.png', type: 'image/png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    	<div class="container">
    		<%= yield %>
    	</div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="row">
  <% @posts.each_slice(1) do |slice| %>
    <% slice.each do |post| -%>
  	<div class="col-md-4">
      <div class="well">
      	<!-- <%= !post.field('Image').blank?  ? image_tag(post.field('Image')) : '' %> -->
      	<%= cms9_field(post.field('Image')) %>
        <%= link_to post.field('Title'), post_path(post.id) %>
        <div><%= post.field('Content') %></div>
       </div>
    </div>
    <%end%>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>TYPE</th>
        <th>DATA</th>
      </tr>
    <% @post.fields.each do |field| %> 
      <tr>
        <td><%=field.id%></td>
        <td><%=field.post_field.name%></td>
        <td><%=field.post_field.field_type%></td>
        <td><%=cms9_field(field).html_safe%></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>